---
- name: copy local ssh to remote hosts
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: copy ssh key
      command: ssh-copy-id marcelo.sales@{{ item }}
      with_items:
        - 172.20.2.81
        - 172.20.2.82
        - 172.20.2.83
