---
- name: "Configure Virtual Machine"
  hosts: domain-admin
  remote_user: admin
  become: true
  become_method: sudo
  gather_facts: yes
  vars:
    - httpd_domain: "{{ansible_default_ipv4.address}}.{{default_domain}}"
  vars_files:
    - playbook-vars.yml
  tasks:
    - name: Undeploy wars
      shell: |
        cd /opt/wildfly/bin
        ./jboss-cli.sh --connect --controller={{wildfly_domain_ip}} --command="undeploy cluster-app.war --all-relevant-server-groups"
        ./jboss-cli.sh --connect --controller={{wildfly_domain_ip}} --command="undeploy counter.war --all-relevant-server-groups"
      when: inventory_hostname in groups['domain-admin']
      ignore_errors: true

    - name: Deploy wars
      shell: |
        cd /opt/wildfly/bin
        ./jboss-cli.sh --connect --controller={{wildfly_domain_ip}} --command="deploy --enabled /opt/cluster-app.war --server-groups=test-server-group"
        ./jboss-cli.sh --connect --controller={{wildfly_domain_ip}} --command="deploy --enabled /opt/counter.war --server-groups=test-server-group"
      when: inventory_hostname in groups['domain-admin']
